config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admin', controllers: { sessions: "admin/sessions", passwords: 'admin/passwords' }

  devise_for :users, skip: [:sessions],
                     path: '',
                     controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  as :user do
    delete 'signout' => 'devise/sessions#destroy', as: :destroy_user_session, path: 'auth'
    get '/auth/:provider/setup' => 'users/omniauth_callbacks#setup', as: :setup_omniauth
  end

  #
  # Sidekiq
  #
  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    Admin.authenticate(username, password)
  end
  mount Sidekiq::Web => '/sidekiq'

  #
  # Websocket
  # 
  get '/socket/:account_id' => 'socket#show'

  #
  # Admin Page
  #
  scope '/admin', as: 'admin' do
    get '/' => 'admin/dashboard#index'

    put '/:language/update' => 'admin/languages#update', as: 'language'

    get '/setting/profile' => 'admin/profile#edit'
    put '/setting/profile' => 'admin/profile#update'

    resources :administrators, controller: 'admin/administrators' do
      resources :permissions, only: [:create, :destroy, :update], controller: 'admin/permissions'
      collection do
        delete 'multi_destroy'
      end
    end

    resources :users, controller: 'admin/users', only: [:edit, :update, :destroy, :index] do
      collection do
        delete 'multi_destroy'
        put    'multi_add_coin'
      end
    end

    resources :pages, controller: 'admin/pages', except: [:show, :new, :create]

    resources :posts, controller: 'admin/posts', except: [:show] do
      collection do
        delete 'multi_destroy'
      end
    end

    resources :categories, controller: 'admin/categories', except: [:show] do
      collection do
        delete 'multi_destroy'
      end
    end

    resources :artists, controller: 'admin/artists', except: [:show] do
      collection do
        delete 'multi_destroy'
      end
    end

    resources :images, controller: 'admin/images', only: [:index, :create, :destroy] do
      collection do
        delete 'multi_destroy'
      end
    end

    resources :tutorials, controller: 'admin/tutorials', except: [:show, :new, :create] do
      collection do
        delete 'multi_destroy'
      end
    end

    resource :crawler, controller: 'admin/crawler', only: [:create, :destroy]

    resources :tabs, controller: 'admin/tabs', except: [:show] do
      collection do
        delete 'multi_destroy'
        get 'multi_upload' => 'admin/multi_upload_tabs#new'
        post 'multi_upload' => 'admin/multi_upload_tabs#create'
      end
    end

    resource :setting, controller: 'admin/setting', only: [:new, :create, :update]

    resource :test_smtp, controller: 'admin/test_smtp', only: [:new, :create]

    scope '/setting', as: 'setting' do
      %w(
        page_info
        social_networks
        seo
        adfly
        smtp
        recaptcha
      ).each do |path|
        get path, to: "admin/setting##{path}"
      end
    end
  end

  # Download url
  get '/download/:hash' => 'download#show', as: 'download'

  # Contact
  post '/contacts' => 'contact#create', as: 'contacts'

  #
  # User Page
  #
  root 'static_pages#locale'

  scope ':language' do
    get '/' => 'static_pages#home'
    resources :tabs, except: [:show], param: 't' do
      member do
        resources :tutorials, only: [:create]
        resource :favorites, only: [:create, :destroy]
      end
    end

    resources :tutorials, except: [:index, :new, :create, :edit, :update, :show, :destroy] do
      member do
        resource :likes, only: [:create, :destroy]
        resource :dislikes, only: [:create, :destroy]
      end
    end

    resources :posts

    get 'profile' => 'users/profile#show'
    get 'profile/tabs' => 'users/tabs#index', as: 'uploaded_tabs'
    delete 'profile/tabs/:t' => 'users/tabs#destroy', as: 'destroy_tab'

    get '/player' => 'tabs#show', as: 'tab_show'

    get '/embed/:sid' => 'embed#show', as: 'embed'

    %w(
      term
      introduce
      privacy
    ).each do |path|
      get path, to: "static_pages##{path}"
    end

    get 'search' => 'search#index'

    get '/contact' => 'contact#index', as: 'contact'

    get '/favorites' => 'favorites#index'
  end

  post '/rate' => 'rater#create', :as => 'rate'

  # devise_for :users, skip: [:sessions],
  #                       path: '',
  #                       controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # as :user do
  #   match 'signout' => 'devise/sessions#destroy', as: :destroy_user_session, path: 'auth', via: Devise.mappings[:user].sign_out_via
  #   get '/auth/:provider/setup' => 'users/omniauth_callbacks#setup', as: :setup_omniauth
  # end
end

app/models/permission.rb
# == Schema Information
#
# Table name: permissions
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Permission < ActiveRecord::Base
  # Validations
  validates :name, presence: true

  # Associations
  has_many :admin_permissions, dependent: :destroy
  has_many :admins, through: :admin_permissions, source: :admin

  def self.filter(admin)
    if admin.permissions.empty?
      self.all
    else
      self.where("id not in (#{admin.permissions.map{ |x| x.id }.join(', ')})")
    end
  end

  def read?(admin_id)
    admin_permissions.find_by(admin_id: admin_id).can_read
  rescue
    false
  end

  def allow_read!(admin_id)
    admin_permissions.find_by(admin_id: admin_id).update can_read: true
  end

  def disable_read!(admin_id)
    admin_permissions.find_by(admin_id: admin_id).update can_read: false
  end

  def create?(admin_id)
    admin_permissions.find_by(admin_id: admin_id).can_create
  rescue
    false
  end

  def disable_create!(admin_id)
    admin_permissions.find_by(admin_id: admin_id).update can_create: false
  end

  def allow_create!(admin_id)
    admin_permissions.find_by(admin_id: admin_id).update can_create: true
  end

  def update?(admin_id)
    admin_permissions.find_by(admin_id: admin_id).can_update
  rescue
    false
  end

  def disable_update!(admin_id)
    admin_permissions.find_by(admin_id: admin_id).update can_update: false
  end

  def allow_update!(admin_id)
    admin_permissions.find_by(admin_id: admin_id).update can_update: true
  end

  def destroy?(admin_id)
    admin_permissions.find_by(admin_id: admin_id).can_destroy
  rescue
    false
  end

  def allow_destroy!(admin_id)
    admin_permissions.find_by(admin_id: admin_id).update can_destroy: true
  end

  def disable_destroy!(admin_id)
    admin_permissions.find_by(admin_id: admin_id).update can_destroy: false
  end
end

app/controllers/admin/administrators_controller.rb
class Admin::AdministratorsController < ApplicationController
  include I18nHelper
  include Admin::AdministratorsHelper
  include Admin::ErrorsHelper

  before_action :authenticate_admin!
  before_action :check_admin_permissions!
  before_action :set_administrator, except: [:index, :new, :create, :multi_destroy]
  before_action :set_page

  layout 'admin_dashboard'

  def index
    @count = Admin.count
    if params[:format] == 'json'
      page = 1
      page = params[:start].to_i / params[:length].to_i + 1 unless params[:start].to_i.zero?

      admins = Admin.filter(params).page(page).per(params[:length].to_i)

      admins_data = []
      admins.each do |admin|
        data = render_admin_as_html(admin)
        admins_data << data
      end

      data = {
        'draw' => params[:draw].to_i,
        'recordsTotal' => admins.count,
        'recordsFiltered' => admins.total_count,
        'data' => admins_data
      }

      render json: data
    end
  rescue => e
    ErrorNotification.send(e)
    render_error_or_redirect
  end

  def new
    @administrator = Admin.new
  end

  def show; end

  def edit; end

  def create
    ActiveRecord::Base.transaction do
      @administrator = Admin.new administrator_params

      if @administrator.save
        flash[:success] = t_scope(params, 'success', name: @administrator.username)
        redirect_to edit_admin_administrator_path(id: @administrator.id)
      else
        render 'new'
      end
    end
  rescue => e
    ErrorNotification.send(e)
    @administrator = Admin.new
    @administrator.errors.add(:system, :error)
    render 'new'
  end

  def destroy
    @errors = []
    @params = params
    unless @administrator.destroy
      @errors << t_scope(params, 'fail', name: @administrator.username)
    end
  rescue => e
    @errors = [I18n.t('alert.system_error')]
    ErrorNotification.send(e)
  end

  def multi_destroy
    ActiveRecord::Base.transaction do
      @errors = []
      @params = params
      @destroyed_administrators = []
      params[:admin_ids].split(',').each do |admin_id|
        administrator = Admin.find_by('email != ? and id = ?', Setting.app_email, admin_id)
        if administrator.nil?
          @errors << I18n.t('administrators.not_found')
          raise ActiveRecord::Rollback
        else
          if administrator.destroy
            @destroyed_administrators << administrator
          else
            @errors << t_scope(params, 'fail', name: administrator.username)
            raise ActiveRecord::Rollback
          end
        end
      end
    end
  rescue => e
    @errors = [I18n.t('alert.system_error')]
    ErrorNotification.send(e)
  end

  private

  def set_page
    @page = 'administrators'
  end

  def set_administrator
    @administrator = begin
                       Admin.find(params[:id])
                     rescue
                       nil
                     end

    @administrator = nil if Setting.app_email.eql?(@administrator.email) && params[:action] != 'show'

    return if @administrator

    if request.xhr?
      @errors = []
      @errors << I18n.t('administrators.not_found')
    else
      flash[:error] = I18n.t('administrators.not_found')
      redirect_to admin_administrators_path
    end
  end

  def administrator_params
    params.require(:admin).permit(
      :email,
      :username,
      :password,
      :password_confirmation,
      :fullname,
      :phone
    )
  end
end

app/helpers/admin/administrators_helper.rb
module Admin::AdministratorsHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::FormTagHelper
  include ActionView::Helpers::AssetTagHelper
  include ActionView::Helpers::UrlHelper
  include ActionView::Helpers::TextHelper
  include ActionView::Context

  def render_admin_as_html(admin)
    checkbox    = admin_checkbox_html(admin)
    avatar      = admin_avatar_html(admin)
    email       = admin.email
    username    = admin.username
    fullname    = admin.fullname
    permissions = admin_permissions_html(admin)
    actions     = admin_actions_html(admin)
    [checkbox, avatar, email, username, fullname, permissions, actions]
  rescue => e
    ErrorNotification.send(e)
    []
  end

  private

  def admin_checkbox_html(admin)
    if Setting.app_email.eql? admin.email
      content_tag :div, class: 'text-center' do
        content_tag :i, '', class: 'fa fa-ban fa-fw'
      end
    else
      content_tag :div, class: 'text-center' do
        check_box_tag 'check-box', admin.id, false, class: 'check-one'
      end
    end
  end

  def admin_avatar_html(admin)
    image_tag admin.avatar, class: 'img-responsive'
  end

  def admin_actions_html(admin)
    content_tag :div, class: 'actions' do
      concat(admin_edit_html(admin))
      concat(admin_delete_html(admin))
    end
  end

  def admin_permissions_html(admin)
    return I18n.t('permissions.no_data') if admin.permissions.empty?
    link_to I18n.t('permissions.view_detail'), admin_administrator_path(admin.id)
  end

  def admin_edit_html(admin)
    return I18n.t('cannot_edit') if Setting.app_email.eql? admin.email

    options = {
      data: { toggle: 'tooltip' },
      title: I18n.t('edit'),
      class: 'btn-edit btn btn-default btn-sm'
    }
    link_to edit_admin_administrator_path(admin.id), options do
      content_tag :i, '', class: 'fa fa-edit'
    end
  end

  def admin_delete_html(admin)
    return '' if Setting.app_email.eql? admin.email

    options = {
      data: {
        admin_username: admin.username,
        admin_id: admin.id,
        href: admin_administrator_path(id: admin.id),
        toggle: 'tooltip'
      },
      title: I18n.t('destroy'),
      class: 'btn-destroy-admin btn btn-danger btn-sm'
    }
    link_to 'javascript:;', options do
      content_tag :i, '', class: 'fa fa-trash-o'
    end
  end
end

app/views/admin/administrators/_modal_add_permissions.html.erb
<div class="modal fade zoom" id="modal-add-permissions">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">
          <%= t('administrators.set_permissions') %>
        </h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <%= label_tag t('administrators.select_permission') %>:
        <%= render 'admin/permissions/permission', id: DateTime.now.to_i %>
        <div class="row add-more">
          <div class='col-sm-12'>
            <%= button_tag '', type: 'button', class: 'btn btn-sm btn-secondary', id: 'btn-add-more-permission' do %>
            <%= t('permissions.add_more') %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <%= submit_tag t('administrators.set_permissions'), class: "btn btn-secondary", id: 'btn-set-permissions' %>
        <button type="button" data-dismiss="modal" aria-label="Close" class="btn btn-default">
          <%= t('cancel') %>
        </button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script type="text/javascript">
$('#modal-add-permissions').on('show.bs.modal', function (e) {
  $(".permission").find('.btn-remove-permission').remove()
})

$("#btn-add-more-permission").click(function(){
  if($(".permission").length >= parseInt("<%= Permission.all.count %>")){
    showMessage("<%= t('permissions.max_selected', count: Permission.all.count) %>", "error")
    return
  }
  $(this).parents('.add-more').before("<%=j render 'admin/permissions/permission', id: DateTime.now.to_i %>")
})

$("#modal-add-permissions").on("click", ".btn-remove-permission", function(){
  $(this).parents('.permission').remove()
})

$("#btn-set-permissions").click(function(){
  $("#modal-add-permissions").find(".btn").prop("disabled", true)
  $("body").css("cursor", "progress")

  permissions = {}

  $(".permission").each(function(){
    permissions[$(this).find('select').val()] = {
      read: $(this).find('input[name=read]').is(':checked'),
      create: $(this).find('input[name=create]').is(':checked'),
      update: $(this).find('input[name=update]').is(':checked'),
      destroy: $(this).find('input[name=destroy]').is(':checked')
    }
  })

  $.ajax({
    type: "POST",
    url: "<%= admin_administrator_permissions_path(administrator_id: @administrator.id) %>",
    data: { permissions: permissions }
  })
})
</script>

app/views/admin/administrators/destroy.js.erb
$('body').css("cursor", 'auto')
$("#modal-confirm-destroy #btn-confirm").removeClass("disabled")
$("#modal-confirm-destroy #btn-cancel").prop("disabled", false)
<% if @errors.empty? %>
showMessage("<%= t_scope(@params, 'success', name: @administrator.username).html_safe %>.", "success")
$('.modal#modal-confirm-destroy').modal('hide');
var row = $(".btn-disable-admin[data-admin-id=<%= @administrator.id %>]").parents('tr')
window.administrators_table.fnDeleteRow(row[0])
object_count = parseInt($('.object-count').text()) - 1
$('.object-count').text(object_count)
<% else %>
showMessage("<%= render_value(@errors) %>", "error")
<% end %>

app/views/admin/administrators/edit.html.erb
<% provide(:og_title, @administrator.username) %>
<% provide(:og_description, Setting.seo_description) %>
<% provide(:keywords, Setting.seo_keywords) %>
<% provide(:meta_image, Setting.featured_image) %>
<div id="page-heading">
  <ol class="breadcrumb">
    <li>
      <%= link_to t('admin.title'), admin_path %>
    </li>
    <li>
      <%= link_to t('.title'), admin_administrators_path %>
    </li>
    <li>
      <%= link_to @administrator.username, admin_administrator_path(@administrator) %>
    </li>
    <li>
      <%= "#{t('edit')}" %>
    </li>
  </ol>
  <h1><%= "#{t('edit')} \"#{@administrator.username}\"" %></h1>
</div>
<div class="container" id="administrator-edit">
  <div class="row">
    <div class="col-md-8">
      <%= image_tag @administrator.avatar, class: 'pull-left', id: 'administrator-avatar' %>
      <div class="table-responsive">
        <table class="table table-condensed">
          <h3><strong><%= @administrator.fullname || t('untitled') %></strong></h3>
          <tbody>
            <tr>
              <td><%= t('.form.username') %></td>
              <td>
                <%= @administrator.username %>
              </td>
            </tr>
            <tr>
              <td><%= t('.form.email') %></td>
              <td>
                <%= link_to @administrator.email, "mailto:#{@administrator.email}" %>
              </td>
            </tr>
            <tr>
              <td>
                <%= t('.form.created_at') %>
              </td>
              <td>
                <%= l(@administrator.created_at, format: :long) %>
              </td>
            </tr>
            <tr>
              <td>
                <%= t('.form.sign_in_count') %>
              </td>
              <td>
                <%= number_with_delimiter(@administrator.sign_in_count) %>
              </td>
            </tr>
            <tr>
              <td>
                <%= t('.form.current_sign_in_at') %>
              </td>
              <td>
                <%= l(@administrator.current_sign_in_at, format: :long) rescue t('unknown') %>
              </td>
            </tr>
            <tr>
              <td>
                <%= t('.form.last_sign_in_at') %>
              </td>
              <td>
                <%= l(@administrator.last_sign_in_at, format: :long) rescue t('unknown') %>
              </td>
            </tr>
            <tr>
              <td>
                <%= t('.form.current_sign_in_ip') %>
              </td>
              <td>
                <%= @administrator.current_sign_in_ip || t('unknown') %>
              </td>
            </tr>
            <tr>
              <td>
                <%= t('.form.last_sign_in_ip') %>
              </td>
              <td>
                <%= @administrator.last_sign_in_ip || t('unknown') %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-8">
      <% if @administrator.admin_permissions.blank? %>
      <div class="alert alert-warning"><%= t('permissions.no_data') %></div>
      <br>
      <% else %>
      <table class="table permissions">
        <thead>
          <tr>
            <th colspan="3">
              <%= t('administrators.set_permissions') %> <strong>(<%= t('administrators.set_permissions_note') %>)</strong>
            </th>
          </tr>
        </thead>
        <tbody>
          <% @administrator.admin_permissions.each do |acp| %>
          <tr>
            <td class="col-sm-3">
              <%= t("permissions.#{acp.permission.name}") %>
            </td>
            <td>
              <%= label_tag 'permission', t('permissions.read'), data: { permission_id: acp.permission.id, action_name: 'read', can_action: acp.permission.read?(@administrator.id) }, class: "label-permission label #{'label-success' if acp.permission.read?(@administrator.id)}" %>
              <%= label_tag 'permission', t('permissions.create'), data: { permission_id: acp.permission.id, action_name: 'create', can_action: acp.permission.create?(@administrator.id) }, class: "label-permission label #{'label-success' if acp.permission.create?(@administrator.id)}" %>
              <%= label_tag 'permission', t('permissions.update'), data: { permission_id: acp.permission.id, action_name: 'update', can_action: acp.permission.update?(@administrator.id) }, class: "label-permission label #{'label-success' if acp.permission.update?(@administrator.id)}" %>
              <%= label_tag 'permission', t('permissions.destroy'), data: { permission_id: acp.permission.id, action_name: 'destroy', can_action: acp.permission.destroy?(@administrator.id) }, class: "label-permission label #{'label-success' if acp.permission.destroy?(@administrator.id)}" %>
            </td>
            <td>
              <%= button_tag '', data: { permission_name: t("permissions.#{acp.permission.name}"), toggle: 'tooltip', href: admin_administrator_permission_path(administrator_id: @administrator.id, id: acp.permission.id) }, title: t('destroy'), class: 'btn btn-danger btn-destroy-permission btn-sm pull-right' do %>
              <i class="fa fa-minus"></i>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <% end %>
      <%= button_tag t('administrators.add_permissions'), class: 'btn btn-sm btn-secondary pull-left', id: 'btn-add-permissions' %>
    </div>
  </div>
</div> <!-- container -->
<script type="text/javascript">
$(".btn-destroy-permission").click(function(){
  $("#launch-modal").html("<%=j render 'shared/modal_confirm_destroy' %>")
  $("#modal-confirm-destroy").find("#btn-confirm").attr("href", $(this).data("href"))
  $("#modal-confirm-destroy").find("#confirm-text").html("<%= t('permissions.title').mb_chars.downcase %> " + $(this).data("permission-name"))
  $("#modal-confirm-destroy").modal({
    keyboard: false,
    backdrop: 'static'
  })
})

$(".label-permission").click(function(){
  $("body").css("cursor", "progress")
  $(".table.permissions .btn").prop("disabled", true)

  permission_id    = $(this).data("permission-id")
  administrator_id = "<%= @administrator.id %>"
  action_name      = $(this).data("action-name")
  can_action       = !$(this).data("can-action")

  $.ajax({
    type: "PUT",
    url: "/admin/administrators/"+administrator_id+"/permissions/"+permission_id,
    data: {action_name: action_name, can_action: can_action}
  })
})

$("#btn-add-permissions").click(function(){
  $("#launch-modal").html("<%=j render 'modal_add_permissions', administrator: @administrator %>")
  $("#modal-add-permissions").modal({
    keyboard: false,
    backdrop: 'static'
  })
})
</script>

app/views/admin/administrators/index.html.erb
<% provide(:og_title, t('.title')) %>
<% provide(:og_description, Setting.seo_description) %>
<% provide(:keywords, Setting.seo_keywords) %>
<% provide(:meta_admin, Setting.featured_image) %>
<div id="page-heading">
  <ol class="breadcrumb">
    <li>
      <%= link_to t('admin.title'), admin_path %>
    </li>
    <li>
      <%= t('.title') %>
    </li>
  </ol>
  <h1>
    <%= t('.title') %>
    <small><strong>(<span class="object-count"><%= number_with_delimiter(@count) %></span>)</strong></small>
    <%= button_tag '', class: 'btn has-text btn-danger btn-action pull-right', id: 'btn-multi-destroy-admins' do %>
    <i class="fa fa-user-times"></i>
    <%= t('.multi_destroy') %>
    <% end %>
    <%= link_to new_admin_administrator_path, class: 'btn pull-right btn-secondary has-text' do %>
    <i class="fa fa-pencil"></i>
    <%= t('.new') %>
    <% end %>
  </h1>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped datatables table-bordered" id="table-administrators">
        <thead>
          <tr>
            <th class="text-center"><%= check_box_tag 'checkbox', '', false, id: 'check-all' %></th>
            <th><%= t('.table.avatar') %></th>
            <th><%= t('.table.email') %></th>
            <th><%= t('.table.username') %></th>
            <th><%= t('.table.fullname') %></th>
            <th><%= t('.table.permissions') %></th>
            <th><%= t('manage') %></th>
          </tr>
        </thead>
        <tbody></tbody>
      </table>
    </div>
  </div>
</div> <!-- container -->
<script type="text/javascript">
$(function(){
  window.selected_id = []
  $("#check-all").click(function () {
    $('.check-one').prop('checked', this.checked);
    showMultiBtnActions();
  });

  $("#table-administrators").on("click", ".check-one", function(){
    if($(".check-one").length == $(".check-one:checked").length) {
      $("#check-all").prop("checked", true);
    } else {
      $("#check-all").prop("checked", false);
    }
    showMultiBtnActions();
  });

  administrators_ajax = {
    url :"<%= admin_administrators_path %>?format=json",
    type: "get"
  }

  window.administrators_table = dataTableInitialize({
    element: $("#table-administrators"),
    un_sorted_arr: [0, 1, 6],
    ajax: administrators_ajax,
    sDom: "<'row'<'col-lg-6'l><'col-lg-6'f>r>t<'row'<'col-lg-12'p>>"
  })

  $("#btn-multi-destroy-admins").click(function(){
    $("#launch-modal").html("<%=j render 'shared/modal_confirm_destroy' %>")
    $("#modal-confirm-destroy").find("#btn-confirm").attr("href", "<%= multi_destroy_admin_administrators_path %>?admin_ids="+window.selected_id.join(','))
    $("#modal-confirm-destroy").find("h2").html("<%= t('.destroy_selected') %>?")
    $("#modal-confirm-destroy").modal({
      keyboard: false,
      backdrop: 'static'
    })
  })

  $("#table-administrators").on("click", ".btn-destroy-admin", function(){
    $("#launch-modal").html("<%=j render 'shared/modal_confirm_destroy' %>")
    $("#modal-confirm-destroy").find("#btn-confirm").attr("href", $(this).data("href"))
    $("#modal-confirm-destroy").find("h2").html("<%= t('.destroy') %> " + $(this).data("admin-username") + "?")
    $("#modal-confirm-destroy").modal({
      keyboard: false,
      backdrop: 'static'
    })
  })
});

function showMultiBtnActions(){
  window.selected_id = []
  if($(".check-one:checked").length > 0){
    $(".btn-action").fadeIn(0)
    $(".check-one:checked").each(function(){
      window.selected_id.push($(this).val())
    })
  }
  else{
    $(".btn-action").fadeOut(0)
    $("#check-all").prop("checked", false);
  }
}
</script>

app/views/admin/administrators/multi_destroy.js.erb
$('body').css("cursor", 'auto')
$("#modal-confirm-destroy #btn-confirm").removeClass("disabled")
$("#modal-confirm-destroy #btn-cancel").prop("disabled", false)
<% if @errors.empty? %>
<% @destroyed_administrators.each do |administrator| %>
showMessage("<%= t_scope(@params, 'success', name: administrator.username).html_safe %>.", "success")
$('.modal#modal-confirm-destroy').modal('hide');
var row = $(".btn-disable-admin[data-admin-id=<%= administrator.id %>]").parents('tr')
window.administrators_table.fnDeleteRow(row[0])
object_count = parseInt($('.object-count').text()) - 1
$('.object-count').text(object_count)
window.selected_id = []
$(".check-one").prop("checked", false)
$("#check-all").prop("checked", false)
<% end %>
<% else %>
showMessage("<%= render_value(@errors) %>", "error")
<% end %>
setTimeout(function(){
  showMultiBtnActions()
}, 200)