config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admin', controllers: { sessions: "admin/sessions", passwords: 'admin/passwords' }

  devise_for :users, skip: [:sessions],
                     path: '',
                     controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  as :user do
    delete 'signout' => 'devise/sessions#destroy', as: :destroy_user_session, path: 'auth'
    get '/auth/:provider/setup' => 'users/omniauth_callbacks#setup', as: :setup_omniauth
  end

  #
  # Sidekiq
  #
  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    Admin.authenticate(username, password)
  end
  mount Sidekiq::Web => '/sidekiq'

  #
  # Websocket
  # 
  get '/socket/:account_id' => 'socket#show'

  #
  # Admin Page
  #
  scope '/admin', as: 'admin' do
    get '/' => 'admin/dashboard#index'

    put '/:language/update' => 'admin/languages#update', as: 'language'

    get '/setting/profile' => 'admin/profile#edit'
    put '/setting/profile' => 'admin/profile#update'

    resources :administrators, controller: 'admin/administrators' do
      resources :permissions, only: [:create, :destroy, :update], controller: 'admin/permissions'
      collection do
        delete 'multi_destroy'
      end
    end

    resources :users, controller: 'admin/users', only: [:edit, :update, :destroy, :index] do
      collection do
        delete 'multi_destroy'
        put    'multi_add_coin'
      end
    end

    resources :pages, controller: 'admin/pages', except: [:show, :new, :create]

    resources :posts, controller: 'admin/posts', except: [:show] do
      collection do
        delete 'multi_destroy'
      end
    end

    resources :categories, controller: 'admin/categories', except: [:show] do
      collection do
        delete 'multi_destroy'
      end
    end

    resources :artists, controller: 'admin/artists', except: [:show] do
      collection do
        delete 'multi_destroy'
      end
    end

    resources :images, controller: 'admin/images', only: [:index, :create, :destroy] do
      collection do
        delete 'multi_destroy'
      end
    end

    resources :tutorials, controller: 'admin/tutorials', except: [:show, :new, :create] do
      collection do
        delete 'multi_destroy'
      end
    end

    resource :crawler, controller: 'admin/crawler', only: [:create, :destroy]

    resources :tabs, controller: 'admin/tabs', except: [:show] do
      collection do
        delete 'multi_destroy'
        get 'multi_upload' => 'admin/multi_upload_tabs#new'
        post 'multi_upload' => 'admin/multi_upload_tabs#create'
      end
    end

    resource :setting, controller: 'admin/setting', only: [:new, :create, :update]

    resource :test_smtp, controller: 'admin/test_smtp', only: [:new, :create]

    scope '/setting', as: 'setting' do
      %w(
        page_info
        social_networks
        seo
        adfly
        smtp
        recaptcha
      ).each do |path|
        get path, to: "admin/setting##{path}"
      end
    end
  end

  # Download url
  get '/download/:hash' => 'download#show', as: 'download'

  # Contact
  post '/contacts' => 'contact#create', as: 'contacts'

  #
  # User Page
  #
  root 'static_pages#locale'

  scope ':language' do
    get '/' => 'static_pages#home'
    resources :tabs, except: [:show], param: 't' do
      member do
        resources :tutorials, only: [:create]
        resource :favorites, only: [:create, :destroy]
      end
    end

    resources :tutorials, except: [:index, :new, :create, :edit, :update, :show, :destroy] do
      member do
        resource :likes, only: [:create, :destroy]
        resource :dislikes, only: [:create, :destroy]
      end
    end

    resources :posts

    get 'profile' => 'users/profile#show'
    get 'profile/tabs' => 'users/tabs#index', as: 'uploaded_tabs'
    delete 'profile/tabs/:t' => 'users/tabs#destroy', as: 'destroy_tab'

    get '/player' => 'tabs#show', as: 'tab_show'

    get '/embed/:sid' => 'embed#show', as: 'embed'

    %w(
      term
      introduce
      privacy
    ).each do |path|
      get path, to: "static_pages##{path}"
    end

    get 'search' => 'search#index'

    get '/contact' => 'contact#index', as: 'contact'

    get '/favorites' => 'favorites#index'
  end

  post '/rate' => 'rater#create', :as => 'rate'

  # devise_for :users, skip: [:sessions],
  #                       path: '',
  #                       controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # as :user do
  #   match 'signout' => 'devise/sessions#destroy', as: :destroy_user_session, path: 'auth', via: Devise.mappings[:user].sign_out_via
  #   get '/auth/:provider/setup' => 'users/omniauth_callbacks#setup', as: :setup_omniauth
  # end
end

app/models/tab.rb
# == Schema Information
#
# Table name: tabs
#
#  id                 :integer          not null, primary key
#  sid                :string(255)
#  title              :string(255)
#  sheet_updated_at   :datetime
#  sheet_file_size    :integer
#  sheet_content_type :string(255)
#  sheet_file_name    :string(255)
#  download_hash      :string(255)
#  download_link      :string(255)
#  adfly_url_id       :string(255)
#  user_id            :integer
#  songsterr_id       :integer
#  status             :integer          default(1)
#  cached_views       :integer          default(0)
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class Tab < ActiveRecord::Base
  include Rails.application.routes.url_helpers
  include Concerns::Tabs::Searchable

  # Attribute accessors
  attr_accessor :seo_title, :seo_keywords, :seo_description, :system

  # Views count
  is_impressionable counter_cache: true, column_name: :cached_views, unique: :all

  # Scope
  scope :published, -> { where(status: 2) }
  scope :viewest, -> { published.order(cached_views: :desc) }
  scope :recently, -> { published.order(created_at: :desc) }
  scope :beginner, -> { published.includes(:rate_average).order('rating_caches.avg asc').where('rating_caches.avg <= 2') }
  scope :unpublish, -> { where(status: 1) }

  # Rate
  ratyrate_rateable 'difficulty'

  # Attachment
  has_attached_file :sheet, url: '/sheets/:sheet_file_name', path: ':rails_root/public:url'

  Paperclip.interpolates :sheet_file_name do |tab, _style|
    tab.instance.sheet_file_name
  end

  # Validate
  validates :title, presence: true, on: :update
  validates_attachment_file_name :sheet, matches: [/gp3\Z/, /gp4\Z/, /gp5\Z/, /gp6\Z/, /gpx\Z/, /ptb\Z/]
  do_not_validate_attachment_file_type :sheet
  validates_attachment_presence :sheet

  # Callback
  after_validation :clean_paperclip_errors
  before_create :set_sid
  before_create :set_title
  before_create :set_download_hash
  before_create :set_sheet_file_name
  before_create :set_download_link
  before_destroy :clear_adfly_link

  # Associations
  has_many :tutorials, dependent: :destroy
  has_one  :rate_average, as: :cacheable, class_name: 'RatingCache', dependent: :destroy
  has_many :tab_artists, dependent: :destroy
  has_many :artists, through: :tab_artists, source: :artist,
                     after_add: [->(a, _c) { Indexer.perform_async(:update, a.class.to_s, a.id) }],
                     after_remove: [->(a, _c) { Indexer.perform_async(:update, a.class.to_s, a.id) }]

  has_many :tab_categories, dependent: :destroy
  has_many :categories, through: :tab_categories,
                        after_add: [->(a, _c) { Indexer.perform_async(:update, a.class.to_s, a.id) }],
                        after_remove: [->(a, _c) { Indexer.perform_async(:update, a.class.to_s, a.id) }]
  has_one :seo, as: :object, dependent: :destroy
  belongs_to :uploader, class_name: 'User', foreign_key: :user_id

  #Delegate
  delegate :title, :keywords, :description, to: :seo, prefix: true, allow_nil: true
  delegate :title, to: :seo, prefix: 'seo_title'
  delegate :keywords, to: :seo, prefix: 'seo_keywords'
  delegate :description, to: :seo, prefix: 'seo_description'

  # Enum
  enum status: { unpublish: 1, published: 2 }

  def seo_title=(*args)
    @seo_title = args[0]
  end

  def seo_title
    seo.title
  rescue
    @seo_title
  end

  def seo_keywords=(*args)
    @seo_keywords = args[0]
  end

  def seo_keywords
    seo.keywords
  rescue
    @seo_keywords
  end

  def seo_description=(*args)
    @seo_description = args[0]
  end

  def seo_description
    seo.description
  rescue
    @seo_description
  end

  def status_locale
    I18n.t("tabs.#{status}")
  end

  def status_enum
    { 'unpublish' => 1, 'published' => 2 }
  end

  def tutorials
    return super.published.most_liked if published?
    return super.unpublish.most_liked if unpublish?
  end

  def published?
    status == 'published'
  end

  def unpublish?
    !published?
  end

  def publish!
    ActiveRecord::Base.transaction do
      update status: 2
    end
  end

  def fill_full_informations?
    return false if artists.empty?
    return false if categories.empty?
    true
  end

  def artists_text
    if artists.empty?
      I18n.t('unknown')
    else
      artists.map(&:name).join(', ')
    end
  rescue
    I18n.t('unknown')
  end

  def categories_text
    if categories.empty?
      I18n.t('unknown')
    else
      categories.map(&:name).join(', ')
    end
  rescue
    I18n.t('unknown')
  end

  def average_score
    Rate.where(rateable_id: id).pluck(:stars).reduce(:+) / Rate.where(rateable_id: id).pluck(:stars).count
  rescue
    0
  end

  def meta_image
    if artists.empty?
      Setting.featured_image
    elsif artists.first.avatar?
      "#{Setting.app_url}#{artists.first.avatar.url(:s300)}"
    else
      Setting.featured_image
    end
  end

  def avatar_url
    if artists.empty?
      "#{Setting.app_url}/missing/artists/avatar/s300/missing.png"
    else
      "#{Setting.app_url}#{artists.first.avatar.url(:s300)}"
    end
  end

  def cover_url
    if artists.empty?
      "#{Setting.app_url}/missing/artists/cover/s800/missing.jpg"
    else
      "#{Setting.app_url}#{artists.first.cover.url(:s800)}"
    end
  end

  def notification_image
    "#{Setting.app_url}#{artists.first.avatar.url(:original)}"
  rescue
    nil
  end

  def as_json(options = {})
    options[:methods] = [:avatar_url, :artists_text, :categories_text]
    super
  end

  class << self
    include Filter

    def filter(params)
      searchable_columns = %w(tabs.id tabs.title)

      search_scope = search_string(searchable_columns, params)

      if params[:order]
        sortable_columns = {
          '2' => 'tabs.title',
          '4' => 'tabs.cached_views',
          '6' => 'tabs.created_at'
        }

        order_scope = sort_string(sortable_columns, params)
      else
        order_scope = 'tabs.created_at desc'
      end

      status = params[:published] == 'true' ? 2 : 1
      where('tabs.status = ?', status).where(search_scope).order(order_scope)
    rescue => e
      ErrorNotification.send(e)
      Kaminari.paginate_array([])
    end
  end


  private

  def set_title
    return unless title.blank?
    self.title = File.basename(sheet_file_name, '.*')
  end

  def clear_adfly_link
    return if self.adfly_url_id.nil?
    if Rails.env.production?
      adfly_api = AdflyApi.new
      response = adfly_api.delete self.adfly_url_id
    end
  end

  def set_download_link
    link = "#{Setting.app_url}#{download_path(hash: download_hash)}"
    if Rails.env.production?
      adfly_api = AdflyApi.new
      response = adfly_api.shorten url: link, advert_type: :int, domain: 'adf.ly', group_id: Setting.adfly_group_id
      if response['errors'] = []
        link = response['data'].first['short_url']
        adfly_url_id = response['data'].first['id']
      end
    end
    self.download_link = link
    self.adfly_url_id  = adfly_url_id
  rescue => e
    ErrorNotification.send(e)
  end

  def set_sheet_file_name
    self.sheet_file_name = loop do
      file_name = SecureRandom.hex + File.extname(sheet_file_name)
      break file_name unless Tab.exists?(sheet_file_name: file_name)
    end
  end

  def set_download_hash
    return if download_hash
    self.download_hash = loop do
      random_download_hash = SecureRandom.hex
      break random_download_hash unless Tab.exists?(download_hash: random_download_hash)
    end
  end

  def set_sid
    return if sid
    self.sid = loop do
      random_sid = [*('a'..'z'), *('A'..'Z')].sample(11).join
      break random_sid unless self.class.exists?(id: random_sid)
    end
  end

  def clean_paperclip_errors
    errors.delete(:sheet_file_name)
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                  :integer          not null, primary key
#  email               :string(255)      default(""), not null
#  encrypted_password  :string(255)      default(""), not null
#  fullname            :string(255)
#  avatar_updated_at   :datetime
#  avatar_file_size    :integer
#  avatar_content_type :string(255)
#  avatar_file_name    :string(255)
#  remember_created_at :datetime
#  sign_in_count       :integer          default(0), not null
#  current_sign_in_at  :datetime
#  last_sign_in_at     :datetime
#  current_sign_in_ip  :string(255)
#  last_sign_in_ip     :string(255)
#  locked_at           :datetime
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#

class User < ActiveRecord::Base
  # Voteable
  acts_as_voter

  # Rate
  ratyrate_rater
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable,
  :trackable, :omniauthable, :validatable

  # Attachments
  has_attached_file :avatar, styles: { s500: '500x500#', s300: '300x300#', s200: '200x200#' },
  default_url: '/missing/avatars/:style/missing.png',
  use_timestamp: false,
  url: '/avatars/:style/:user_id:user_avatar_ext',
  path: ':rails_root/public:url'

  Paperclip.interpolates :user_id do |user, _style|
    "#{format('IMG%010d', user.instance.id)}"
  end

  Paperclip.interpolates :user_avatar_ext do |user, _style|
    ".#{user.instance.avatar_content_type.split('/').last}"
  end

  # Validates
  do_not_validate_attachment_file_type :avatar
  validates :fullname, presence: true
  validates_attachment_presence :avatar

  # Callbacks
  after_save :set_avatar_file_name

  # Associations
  has_many :tabs, dependent: :destroy
  has_many :tab_favorites, dependent: :destroy
  has_many :favorite_tabs, through: :tab_favorites

  # Check user is locked
  def locked?
    !locked_at.nil?
  end

  class << self
    include Filter

    def filter(params)
      searchable_columns = %w(id email fullname)

      search_scope = search_string(searchable_columns, params)

      if params[:order]
        sortable_columns = {
          '2' => 'email',
          '3' => 'fullname',
          '4' => 'created_at'
        }

        order_scope = sort_string(sortable_columns, params)
      else
        order_scope = 'created_at desc'
      end

      where(search_scope).order(order_scope)
    rescue => e
      ErrorNotification.send(e)
      Kaminari.paginate_array([])
    end

    # Oauth
    def find_for_facebook_oauth(auth)
      user = User.find_by(email: auth.info.email)

      user_params = {
        avatar: "#{auth.info.image}?type=large".gsub('http://', 'https://'),
        fullname: auth.extra.raw_info.name
      }

      if user
        user.update user_params
      else
        user_params[:email] = auth.info.email
        user_params[:password] = Devise.friendly_token[0, 8]
        user = User.create user_params
      end

      user
    rescue => e
      ErrorNotification.send(e)
    end

    def find_for_google_oauth2(auth)
      user = User.find_by(email: auth.info.email)

      user_params = {
        avatar: "#{auth.info.image.split('?sz')[0]}?sz=500".gsub('http://', 'https://'),
        fullname: auth.info.name
      }

      if user
        user.update user_params
      else
        user_params[:email] = auth.info.email
        user_params[:password] = Devise.friendly_token[0, 8]
        user = User.create user_params
      end

      user
    rescue => e
      ErrorNotification.send(e)
    end
  end

  private

  def set_avatar_file_name
    file_name = "#{format('IMG%010d', id)}.#{avatar_content_type.split('/').last}"
    return if avatar_file_name == file_name
    self.avatar_file_name = file_name
  rescue => e
    ErrorNotification.send(e)
  end
end

app/helpers/tabs_helper.rb
module TabsHelper
end

app/views/admin/tabs/_modal_confirm_crawler.html.erb
<div class="modal fade zoom modal-confirm" id="modal-confirm-crawler">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <%= form_tag admin_crawler_path, method: "post", remote: true do %>
        <center>
          <h1>
            <i class="text-secondary fa fa-refresh"></i>
          </h1>
          <h2>
            <%= t('.are_you_sure') %>?
          </h2>
          <%= button_tag '', id: 'btn-confirm', class: 'btn btn-secondary' do %>
            <%= t('accept') %>
          <% end %>
          <button id="btn-cancel" type="button" data-dismiss="modal" aria-label="Close" class="btn btn-default">
            <%= t('cancel') %>
          </button>
        </center>
        <% end %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script type="text/javascript">
$("#btn-confirm").click(function(){
  $('body').css("cursor", 'progress')
  $("#modal-confirm-crawler #btn-confirm").addClass("disabled")
  $("#modal-confirm-crawler #btn-cancel").prop("disabled", true)
})
</script>

app/views/admin/tabs/_modal_confirm_stop_crawler.html.erb
<div class="modal fade zoom modal-confirm" id="modal-confirm-stop-crawler">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <center>
          <h1>
            <i class="text-danger fa fa-warning"></i>
          </h1>
          <h2>
            <%= t('.are_you_sure') %>?
          </h2>
          <a data-remote="true" data-method="DELETE" href="<%= admin_crawler_path %>" id="btn-confirm" class="btn btn-danger">
            <%= t('accept') %>
          </a>
          <button id="btn-cancel" type="button" data-dismiss="modal" aria-label="Close" class="btn btn-default">
            <%= t('cancel') %>
          </button>
        </center>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script type="text/javascript">
$("#btn-confirm").click(function(){
  $('body').css("cursor", 'progress')
  $("#modal-confirm-stop-crawler #btn-confirm").addClass("disabled")
  $("#modal-confirm-stop-crawler #btn-cancel").prop("disabled", true)
})
</script>

app/views/admin/tabs/edit.html.erb
<% provide(:og_title, t('.title')) %>
<% provide(:og_description, Setting.seo_description) %>
<% provide(:keywords, Setting.seo_keywords) %>
<% provide(:meta_image, Setting.featured_image) %>
<%= form_for @tab, url: admin_tab_path(@tab), method: 'put' do |f| %>
<div id="page-heading">
  <ol class="breadcrumb">
    <li>
      <%= link_to t('admin.title'), admin_path %>
    </li>
    <li>
      <%= link_to t('admin.tabs.index.title'), admin_tabs_path %>
    </li>
    <li>
      <%= link_to @tab.title, edit_admin_tab_path(@tab) %>
    </li>
    <li>
      <%= "#{t('edit')}" %>
    </li>
  </ol>
  <h1>
    <%= t('.title') %>
  </h1>
</div>
<div class="container new-tab">
  <div class="col-md-9">
    <div class="form-group <%= 'has-error' if @tab.errors.has_key?(:title) %>">
      <%= f.text_field :title, class: 'form-control input-lg', placeholder: t('.form.title_placeholder') %>
      <p class="help-block">
        <% if @tab.errors.has_key?(:title) %>
        <%= @tab.errors[:title].join('<br>').html_safe %>
        <% end %>
      </p>
    </div>
    <div class="form-group">
      <%= f.label :artists, class: 'control-label' %>
      <%= f.select :artist_ids, @tab.artists.collect { |x| [x.name, x.id] }, {}, class: "form-control select-artists", multiple: true %>
    </div>
    <div class="form-group">
      <%= f.label :categories, class: 'control-label' %>
      <%= f.select :category_ids, Category.all.collect { |x| [x.name, x.id] }, {}, class: "form-control", multiple: true %>
    </div>
    <div class="form-group">
      <%= f.label :status, class: 'control-label' %>
      <div class="tab-status">
        <label>
          <%= f.radio_button :status, true, checked: @tab.status == 'published' %>
          <%= t('tabs.published') %>
        </label>
        <label>
          <%= f.radio_button :status, false, checked: @tab.status == 'unpublish' %>
          <%= t('tabs.unpublish') %>
        </label>
      </div>
    </div>
    <div class="panel panel-default">
      <a data-toggle="collapse" href="#seo-setting" class="">
        <div class="panel-heading">
          <h4><%= t('.form.setting_seo') %></h4>
        </div>
      </a>
      <div id="seo-setting" class="panel-collapse in">
        <div class="panel-body form-horizontal">
          <div class="row seo-preview">
            <div class="col-md-12">
              <span class="seo-title">
                <span class="title-text"><%= @tab.seo_title.blank? ? @tab.title : @tab.seo_title %></span>
                - <%= Setting.app_name %>
              </span>
              <span class="seo-url">
                <%= "#{Setting.app_url.gsub('http://', '')}" %>/<%= I18n.locale %>/player?t=<span class="url-text"><%= "#{@tab.sid}" unless @tab.title.blank? %></span>
              </span>
              <span class="seo-description">
                <%= @tab.seo_description.blank? ? t('.form.seo_description_note') : @tab.seo_description %>
              </span>
            </div>
          </div>
          <br><br>
          <div class="form-group">
            <%= f.label :seo_title, class: 'col-sm-2 control-label' %>
            <div class="col-md-10">
              <%= f.text_field :seo_title, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :seo_keywords, class: 'col-sm-2 control-label' %>
            <div class="col-md-10">
              <%= f.text_field :seo_keywords, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :seo_description, class: 'col-sm-2 control-label' %>
            <div class="col-md-10">
              <%= f.text_area :seo_description, class: "form-control", rows: 5 %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="panel panel-default">
      <a data-toggle="collapse" href="#update-tab" class="">
        <div class="panel-heading">
          <h4><%= t('.title') %></h4>
        </div>
      </a>
      <div id="update-tab" class="panel-collapse in">
        <div class="panel-body">
          <div class="form">
            <%= f.label :status, class: "control-label" %>:
            <b><%= @tab.status_locale %></b>
          </div>
          <div class="form">
            <%= f.label :created_at, class: "control-label" %>:
            <%= l(@tab.created_at, format: :datetime) %>
          </div>
          <div class="form">
            <%= f.label :updated_at, class: "control-label" %>:
            <%= l(@tab.updated_at, format: :datetime) %>
          </div>
        </div>
        <div class="panel-footer">
          <div class="row">
            <div class="col-md-12">
              <%= link_to t('cancel'), admin_tabs_path, class: 'btn btn-default pull-left' %>
              <%= f.submit t('save'), class: 'btn btn-secondary pull-right' %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <a data-toggle="collapse" href="#tab-image-panel" class="">
        <div class="panel-heading">
          <h4><%= t('.form.featured_image') %></h4>
        </div>
      </a>
      <div id="tab-image-panel" class="panel-collapse in">
        <div class="panel-body">
          <div class="row">
            <div class="col-md-12">
              <div class="tab-image">
                <% unless @tab.avatar_url.blank? %>
                <%= image_tag @tab.avatar_url, class: 'select-tab-image' %>
                <br>
                <br>
                <% end %>
              </div>
              <small class="text-danger">* <%= t('.form.featured_image_note') %></small>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div> <!-- container -->
<% end %>
<script type="text/javascript">
$("#tab_seo_title").keyup(function(){
  $(".seo-title .title-text").text($(this).val())
})

$("#tab_seo_description").keyup(function(){
  if($(this).val() == "")
    $(".seo-description").text("<%= t('.form.seo_description_note') %>")
  else
    $(".seo-description").text($(this).val())
})

data = []
<% @tab.artists.each do |artist| %>
data.push({
  id: "<%= artist.id %>",
  name: "<%= artist.name %>",
  avatar_url: "<%= artist.avatar_url %>"
})
<% end %>

$(".select-artists").select2({
  tags: true,
  data: data,
  language: "<%= I18n.locale %>",
  placeholder: "<%= t('.form.artist_placeholder') %>",
  ajax: {
    url: "<%= admin_artists_path(type: 'search') %>",
    dataType: "json",
    delay: 250,
    data: function (params) {
      return {
        q: params.term,
        page: params.page
      };
    },
    processResults: function (data, params) {
      return {
        results: data
      };
    },
    cache: true
  },
  escapeMarkup: function (markup) { return markup; },
  minimumInputLength: 1,
  templateResult: formatRepo,
  templateSelection: formatRepoSelection
}).on("select2:select", function(e) {
  avatar_url = $(".select-artists").select2('data')[0].avatar_url
  $(".select-tab-image").attr("src", avatar_url)
}).on("select2:unselect", function(e) {
  if($(".select-artists").select2('data').length == 0)
    $(".select-tab-image").attr("src", '<%= "#{Setting.app_url}/missing/artists/avatar/s800/missing.png" %>')
  else{
    avatar_url = $(".select-artists").select2('data')[0].avatar_url
    $(".select-tab-image").attr("src", avatar_url)
  }
});

$("#tab_category_ids").select2({
  tags: true,
  language: "<%= I18n.locale %>",
  placeholder: "<%= t('.form.category_placeholder') %>",
  createTag: function () {
    return null;
  }
})

function formatRepo (repo) {
  if (repo.loading) return repo.text;
  if(typeof repo.avatar_url !== "undefined")
  {
    var markup = "<div class='select2-artist clearfix'>" +
    "<div class='artist-avatar'><img src='" + repo.avatar_url + "' /></div>" +
    "<div class='artist-meta'>" +
    "<div class='artist-name'>" + repo.name + "</div></div>";
  }
  else {
    markup = "<div class='artist-name'>" + repo.text + "</div>"
  }

  return markup;
}

function formatRepoSelection (repo) {
  return repo.name || repo.text;
}
</script>