config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admin', controllers: { sessions: "admin/sessions", passwords: 'admin/passwords' }

  devise_for :users, skip: [:sessions],
                     path: '',
                     controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  as :user do
    delete 'signout' => 'devise/sessions#destroy', as: :destroy_user_session, path: 'auth'
    get '/auth/:provider/setup' => 'users/omniauth_callbacks#setup', as: :setup_omniauth
  end

  #
  # Sidekiq
  #
  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    Admin.authenticate(username, password)
  end
  mount Sidekiq::Web => '/sidekiq'

  #
  # Websocket
  # 
  get '/socket/:account_id' => 'socket#show'

  #
  # Admin Page
  #
  scope '/admin', as: 'admin' do
    get '/' => 'admin/dashboard#index'

    put '/:language/update' => 'admin/languages#update', as: 'language'

    get '/setting/profile' => 'admin/profile#edit'
    put '/setting/profile' => 'admin/profile#update'

    resources :administrators, controller: 'admin/administrators' do
      resources :permissions, only: [:create, :destroy, :update], controller: 'admin/permissions'
      collection do
        delete 'multi_destroy'
      end
    end

    resources :users, controller: 'admin/users', only: [:edit, :update, :destroy, :index] do
      collection do
        delete 'multi_destroy'
        put    'multi_add_coin'
      end
    end

    resources :pages, controller: 'admin/pages', except: [:show, :new, :create]

    resources :posts, controller: 'admin/posts', except: [:show] do
      collection do
        delete 'multi_destroy'
      end
    end

    resources :categories, controller: 'admin/categories', except: [:show] do
      collection do
        delete 'multi_destroy'
      end
    end

    resources :artists, controller: 'admin/artists', except: [:show] do
      collection do
        delete 'multi_destroy'
      end
    end

    resources :images, controller: 'admin/images', only: [:index, :create, :destroy] do
      collection do
        delete 'multi_destroy'
      end
    end

    resources :tutorials, controller: 'admin/tutorials', except: [:show, :new, :create] do
      collection do
        delete 'multi_destroy'
      end
    end

    resource :crawler, controller: 'admin/crawler', only: [:create, :destroy]

    resources :tabs, controller: 'admin/tabs', except: [:show] do
      collection do
        delete 'multi_destroy'
        get 'multi_upload' => 'admin/multi_upload_tabs#new'
        post 'multi_upload' => 'admin/multi_upload_tabs#create'
      end
    end

    resource :setting, controller: 'admin/setting', only: [:new, :create, :update]

    resource :test_smtp, controller: 'admin/test_smtp', only: [:new, :create]

    scope '/setting', as: 'setting' do
      %w(
        page_info
        social_networks
        seo
        adfly
        smtp
        recaptcha
      ).each do |path|
        get path, to: "admin/setting##{path}"
      end
    end
  end

  # Download url
  get '/download/:hash' => 'download#show', as: 'download'

  # Contact
  post '/contacts' => 'contact#create', as: 'contacts'

  #
  # User Page
  #
  root 'static_pages#locale'

  scope ':language' do
    get '/' => 'static_pages#home'
    resources :tabs, except: [:show], param: 't' do
      member do
        resources :tutorials, only: [:create]
        resource :favorites, only: [:create, :destroy]
      end
    end

    resources :tutorials, except: [:index, :new, :create, :edit, :update, :show, :destroy] do
      member do
        resource :likes, only: [:create, :destroy]
        resource :dislikes, only: [:create, :destroy]
      end
    end

    resources :posts

    get 'profile' => 'users/profile#show'
    get 'profile/tabs' => 'users/tabs#index', as: 'uploaded_tabs'
    delete 'profile/tabs/:t' => 'users/tabs#destroy', as: 'destroy_tab'

    get '/player' => 'tabs#show', as: 'tab_show'

    get '/embed/:sid' => 'embed#show', as: 'embed'

    %w(
      term
      introduce
      privacy
    ).each do |path|
      get path, to: "static_pages##{path}"
    end

    get 'search' => 'search#index'

    get '/contact' => 'contact#index', as: 'contact'

    get '/favorites' => 'favorites#index'
  end

  post '/rate' => 'rater#create', :as => 'rate'

  # devise_for :users, skip: [:sessions],
  #                       path: '',
  #                       controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # as :user do
  #   match 'signout' => 'devise/sessions#destroy', as: :destroy_user_session, path: 'auth', via: Devise.mappings[:user].sign_out_via
  #   get '/auth/:provider/setup' => 'users/omniauth_callbacks#setup', as: :setup_omniauth
  # end
end

app/models/setting.rb
# == Schema Information
#
# Table name: settings
#
#  id                        :integer          not null, primary key
#  app_name                  :string(255)
#  app_url                   :string(255)
#  app_email                 :string(255)
#  app_phone                 :string(255)
#  app_hotline               :string(255)
#  app_fax                   :string(255)
#  app_address               :string(255)
#  facebook_fanpage          :string(255)
#  facebook_app_id           :string(255)
#  facebook_app_secret       :string(255)
#  google_api_key            :string(255)
#  google_app_id             :string(255)
#  google_app_secret         :string(255)
#  google_analytics_id       :string(255)
#  youtube_endpoint          :string(255)
#  youtube_thumbnail         :string(255)
#  youtube_api_key           :string(255)
#  adfly_uid                 :string(255)
#  adfly_key                 :string(255)
#  adfly_secret_key          :string(255)
#  adfly_group_id            :string(255)
#  adfly_endpoint            :string(255)
#  smtp_sender               :string(255)
#  smtp_address              :string(255)
#  smtp_port                 :integer
#  smtp_username             :string(255)
#  smtp_password             :string(255)
#  smtp_authentication       :string(255)
#  smtp_enable_starttls_auto :boolean
#  recaptcha_publickey       :string(255)
#  recaptcha_privatekey      :string(255)
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#

class Setting < ActiveRecord::Base
  # Attribute accessors
  attr_accessor :admin_username, :admin_password, :keywords, :description, :featured_image, :system

  # Association
  has_one :seo, as: :object, dependent: :destroy

  # Validations
  validates :app_name, presence: true
  validates :app_url, url: true
  validates :app_email, email: true
  validates :admin_username, presence: true, on: :create
  validates_format_of :admin_username, with: /^[a-zA-Z0-9_\.]*$/, multiline: true, on: :create
  validates :admin_password, length: { within: 6..30 }, on: :create
  validates :facebook_fanpage, on: :update, url: true, allow_nil: true
  validates :youtube_endpoint, on: :update, url: true, allow_nil: true
  validates :youtube_thumbnail, on: :update, url: true, allow_nil: true
  validates :smtp_username, on: :update, email: true, allow_nil: true

  delegate :keywords, to: :seo
  delegate :description, to: :seo
  delegate :featured_image, to: :seo

  class << self
    def app_name
      Setting.first.app_name
    rescue
      nil
    end

    def app_url
      Setting.first.app_url
    rescue
      nil
    end

    def app_email
      Setting.first.app_email
    rescue
      nil
    end

    def app_phone
      Setting.first.app_phone
    rescue
      nil
    end

    def app_hotline
      Setting.first.app_hotline
    rescue
      nil
    end

    def app_fax
      Setting.first.app_fax
    rescue
      nil
    end

    def app_address
      Setting.first.app_address
    rescue
      nil
    end

    def seo_keywords
      Setting.first.keywords
    rescue
      nil
    end

    def seo_description
      Setting.first.description
    rescue
      nil
    end

    def featured_image
      Setting.first.featured_image || "#{Setting.app_url}#{ActionController::Base.helpers.asset_path('setting/missing.png')}"
    rescue
      "#{Setting.app_url}#{ActionController::Base.helpers.asset_path('setting/missing.png')}"
    end

    def facebook_fanpage
      Setting.first.facebook_fanpage
    rescue
      nil
    end

    def facebook_app_id
      Setting.first.facebook_app_id
    rescue
      nil
    end

    def facebook_app_secret
      Setting.first.facebook_app_secret
    rescue
      nil
    end

    def google_api_key
      Setting.first.google_api_key
    rescue
      nil
    end

    def google_app_id
      Setting.first.google_app_id
    rescue
      nil
    end

    def google_app_secret
      Setting.first.google_app_secret
    rescue
      nil
    end

    def google_analytics_id
      Setting.first.google_analytics_id
    rescue
      nil
    end

    def youtube_endpoint
      Setting.first.youtube_endpoint
    rescue
      nil
    end

    def youtube_thumbnail
      Setting.first.youtube_thumbnail
    rescue
      nil
    end

    def youtube_api_key
      Setting.first.youtube_api_key
    rescue
      nil
    end

    def adfly_uid
      Setting.first.adfly_uid
    rescue
      nil
    end

    def adfly_key
      Setting.first.adfly_key
    rescue
      nil
    end

    def adfly_secret_key
      Setting.first.adfly_secret_key
    rescue
      nil
    end

    def adfly_group_id
      Setting.first.adfly_group_id
    rescue
      nil
    end

    def adfly_endpoint
      Setting.first.adfly_endpoint
    rescue
      nil
    end

    def smtp_sender
      Setting.first.smtp_sender
    rescue
      nil
    end

    def smtp_address
      Setting.first.smtp_address
    rescue
      nil
    end

    def smtp_port
      Setting.first.smtp_port
    rescue
      nil
    end

    def smtp_username
      Setting.first.smtp_username
    rescue
      nil
    end

    def smtp_password
      Setting.first.smtp_password
    rescue
      nil
    end

    def smtp_authentication
      Setting.first.smtp_authentication
    rescue
      nil
    end

    def smtp_enable_starttls_auto
      Setting.first.smtp_enable_starttls_auto
    rescue
      nil
    end

    def recaptcha_publickey
      Setting.first.recaptcha_publickey
    rescue
      nil
    end

    def recaptcha_private_key
      Setting.first.recaptcha_private_key
    rescue
      nil
    end
  end
end

app/controllers/admin/setting_controller.rb
class Admin::SettingController < ApplicationController
  include I18nHelper

  layout :set_layout

  skip_before_action :setup_setting!, only: [:new, :create]
  before_action :authenticate_admin!, except: [:new, :create]
  before_action :check_admin_permissions!, except: [:new, :create]
  before_action :set_page, except: [:new, :create]
  before_action :set_setting, except: [:new, :create]

  def new
    redirect_to admin_path if Setting.first
    @setting = Setting.new
  end

  def create
    redirect_to admin_path if Setting.first
    @setting = Setting.new setting_params
    ActiveRecord::Base.transaction do
      if @setting.save
        I18n.locale = :en
        @setting.seo = Seo.create object_id: @setting.id, object_type: 'Setting'
        I18n.locale = :vi
        @setting.seo = Seo.create object_id: @setting.id, object_type: 'Setting'
        @admin = Admin.new admin_params
        if @admin.save
          Permission.all.each do |permission|
            @admin.permissions << permission
            @admin.save
            permission.allow_read!(@admin.id)
            permission.allow_create!(@admin.id)
            permission.allow_update!(@admin.id)
            permission.allow_destroy!(@admin.id)
          end
        end
        flash[:success] = t_scope(params, 'success')
        sign_in @admin
        redirect_to admin_path
      else
        render 'new'
      end
    end
  rescue => e
    ErrorNotification.send(e)
    flash[:error] = "#{I18n.t('alert.system_error')}."
    redirect_to new_admin_setting_path
  end

  def update
    @current_tab = params[:update_type]
    if @current_tab == 'seo'
      if @setting.seo.update seo_params
        flash[:success] = t_scope(params, 'success')
        redirect_to params[:redirect_path]
      else
        render params[:update_type]
      end
    elsif @setting.update update_params
      flash[:success] = t_scope(params, 'success')
      redirect_to params[:redirect_path]
    else
      render params[:update_type]
    end
  rescue => e
    ErrorNotification.send(e)
    flash[:error] = @errors = I18n.t('alert.system_error')
    redirect_to admin_path
  end

  private

  def setting_params
    params.require(:setting).permit(:app_name, :app_url, :app_email, :admin_username, :admin_password)
  end

  def admin_params
    params[:admin] = {
      email: params[:setting][:app_email],
      username: params[:setting][:admin_username],
      password: params[:setting][:admin_password]
    }
    params.require(:admin).permit(:username, :email, :password)
  end

  def update_params
    params[:setting].each do |key, value|
      params[:setting][key] = nil if value.blank?
    end

    params.require(:setting).permit(
      :app_name,
      :app_url,
      :app_email,
      :app_address,
      :app_phone,
      :app_fax,
      :app_hotline,
      :facebook_fanpage,
      :facebook_app_id,
      :facebook_app_secret,
      :google_api_key,
      :google_app_id,
      :google_app_secret,
      :google_analytics_id,
      :youtube_endpoint,
      :youtube_thumbnail,
      :youtube_api_key,
      :adfly_uid,
      :adfly_key,
      :adfly_secret_key,
      :adfly_group_id,
      :adfly_endpoint,
      :smtp_sender,
      :smtp_address,
      :smtp_port,
      :smtp_username,
      :smtp_password,
      :smtp_authentication,
      :smtp_enable_starttls_auto,
      :recaptcha_publickey,
      :recaptcha_privatekey
    )
  end

  def seo_params
    params[:setting].each do |key, value|
      params[:setting][key] = nil if value.blank?
    end

    params.require(:setting).permit(:keywords, :description, :featured_image)
  end

  def set_setting
    @setting = Setting.first
  end

  def set_page
    @page = 'setting'
    @current_tab = params[:action]
  end

  def check_admin_permissions!
    admin_id      = current_admin.id
    access_denied = begin
      case params[:action]
      when 'update'
        !current_admin.permissions.find_by(name: 'setting').update?(admin_id)
      else
        !current_admin.permissions.find_by(name: 'setting').read?(admin_id)
      end
    rescue
      true
    end

    return unless access_denied
    if request.xhr?
      @errors = [I18n.t('permissions.access_denied')]
      respond_to do |format|
        format.js
      end
    else
      flash[:error] = I18n.t('permissions.access_denied')
      redirect_to admin_path
    end
  end

  def set_layout
    return 'admin_auth' if %w(new create).include? params[:action]
    return 'admin_dashboard'
  end
end

app/helpers/admin/setting_helper.rb
module Admin::SettingHelper
end

app/views/admin/setting/_facebook_setting.html.erb
<h4><b><%= t('.title') %></b></h4>
<div class="row">
  <div class="col-md-12">
    <div class="form-group row <%= 'has-error' if @setting.errors.has_key?(:facebook_fanpage) %>">
      <%= f.label :facebook_fanpage, class: 'control-label col-md-2 col-sm-4'  %>
      <div class="col-md-6 col-sm-8">
        <%= f.text_field :facebook_fanpage, class: "form-control" %>
        <p class="help-block">
          <% if @setting.errors.has_key?(:facebook_fanpage) %>
          <%= @setting.errors[:facebook_fanpage].join('<br>').html_safe %>
          <% end %>
        </p>
      </div>
    </div>
    <div class="form-group row <%= 'has-error' if @setting.errors.has_key?(:facebook_app_id) %>">
      <%= f.label :facebook_app_id, class: 'control-label col-md-2 col-sm-4'  %>
      <div class="col-md-6 col-sm-8">
        <%= f.text_field :facebook_app_id, class: "form-control" %>
        <p class="help-block">
          <% if @setting.errors.has_key?(:facebook_app_id) %>
          <%= @setting.errors[:facebook_app_id].join('<br>').html_safe %>
          <% end %>
        </p>
      </div>
    </div>
    <div class="form-group row <%= 'has-error' if @setting.errors.has_key?(:facebook_app_secret) %>">
      <%= f.label :facebook_app_secret, class: 'control-label col-md-2 col-sm-4'  %>
      <div class="col-md-6 col-sm-8">
        <%= f.text_field :facebook_app_secret, class: "form-control" %>
        <p class="help-block">
          <% if @setting.errors.has_key?(:facebook_app_secret) %>
          <%= @setting.errors[:facebook_app_secret].join('<br>').html_safe %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/admin/setting/_setting_tabs.html.erb
<ul class="nav nav-tabs">
  <li class="<%= 'active' if @current_tab == 'page_info' %>">
    <%= link_to t('.page_info'), admin_setting_page_info_path %>
  </li>
  <li class="<%= 'active' if @current_tab == 'social_networks' %>">
    <%= link_to t('.social_networks'), admin_setting_social_networks_path %>
  </li>
  <li class="<%= 'active' if @current_tab == 'adfly' %>">
    <%= link_to t('.adfly'), admin_setting_adfly_path %>
  </li>
  <li class="<%= 'active' if @current_tab == 'seo' %>">
    <%= link_to t('.seo'), admin_setting_seo_path %>
  </li>
  <li class="<%= 'active' if @current_tab == 'smtp' %>">
    <%= link_to t('.smtp'), admin_setting_smtp_path %>
  </li>
  <li class="<%= 'active' if @current_tab == 'recaptcha' %>">
    <%= link_to t('.recaptcha'), admin_setting_recaptcha_path %>
  </li>
</ul>

app/views/admin/setting/_test_smtp.html.erb
<h4><b><%= t('.title') %></b></h4>
<div class="row" id="test-smtp">
  <div class="col-md-12">
    <div class='form-group row'>
      <%= label_tag 'email', t('.form.mail_to'), class: 'control-label col-md-2 col-sm-3' %>
      <div class="col-md-6 col-sm-6">
        <%= text_field_tag :test_email, nil, class: 'form-control' %>
        <p class="help-block"></p>
        <div class="alert" id="test-smtp-alert">
          <div class="alert-icon">
          </div>
          <div class="alert-text">
          </div>
        </div>
      </div>
      <div class="col-md-2 col-sm-3">
        <%= button_tag t('.form.submit'), type: 'button', id: 'btn-test-smtp', class: 'btn btn-secondary' %>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
$('#test_email').on('keyup keypress', function(e) {
  var keyCode = e.keyCode || e.which;
  if (keyCode === 13) { 
    e.preventDefault();
    $("#btn-test-smtp").click()
    return false;
  }
});

$("#btn-test-smtp").click(function(){
  $(".tab-content .btn").prop("disabled", true)
  $("body").css("cursor", "progress")
  $.ajax({
    type: "GET",
    url: "<%= new_admin_test_smtp_path %>",
    data: { email: $("#test_email").val() }
  })
})
</script>

app/views/admin/setting/new.html.erb
<% provide(:og_title, t('.title')) %>
<%= form_for @setting, url: admin_setting_path, method: 'post' do |f| %>
<div class="panel-body">
  <h4 class="text-center">
    <%= t('.title') %>
  </h4>
  <% flash.each do |key, value| %>
  <% if value %>
  <div class="alert alert-<%= render_key(key) %>">
    <ul>
      <li><%= value.html_safe %></li>
    </ul>
  </div>
  <br>
  <% end %>
  <% end %>
  <div class="form-group <%= 'has-error' if @setting.errors.has_key?(:app_name) %>">
    <div class="row">
      <div class="col-sm-12">
        <div class="input-group">
          <span class="input-group-addon"><i class="fa fa-edit"></i></span>
          <%= f.text_field :app_name, autofocus: true, placeholder: t('.form.app_name'), class: "form-control" %>
        </div>
        <p class="help-block">
          <% if @setting.errors.has_key?(:app_name) %>
          <%= @setting.errors[:app_name].join('<br>').html_safe %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
  <div class="form-group <%= 'has-error' if @setting.errors.has_key?(:app_url) %>">
    <div class="row">
      <div class="col-sm-12">
        <div class="input-group">
          <span class="input-group-addon"><i class="fa fa-globe"></i></span>
          <%= f.text_field :app_url, autofocus: true, placeholder: t('.form.app_url'), class: "form-control" %>
        </div>
        <p class="help-block">
          <% if @setting.errors.has_key?(:app_url) %>
          <%= @setting.errors[:app_url].join('<br>').html_safe %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
  <div class="form-group <%= 'has-error' if @setting.errors.has_key?(:app_email) %>">
    <div class="row">
      <div class="col-sm-12">
        <div class="input-group">
          <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
          <%= f.text_field :app_email, autofocus: true, placeholder: t('.form.app_email'), class: "form-control" %>
        </div>
        <p class="help-block">
          <% if @setting.errors.has_key?(:app_email) %>
          <%= @setting.errors[:app_email].join('<br>').html_safe %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
  <div class="form-group <%= 'has-error' if @setting.errors.has_key?(:admin_username) %>">
    <div class="row">
      <div class="col-sm-12">
        <div class="input-group">
          <span class="input-group-addon"><i class="fa fa-user-secret"></i></span>
          <%= f.text_field :admin_username, autofocus: true, placeholder: t('.form.admin_username'), class: "form-control" %>
        </div>
        <p class="help-block">
          <% if @setting.errors.has_key?(:admin_username) %>
          <%= @setting.errors[:admin_username].join('<br>').html_safe %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
  <div class="form-group <%= 'has-error' if @setting.errors.has_key?(:admin_password) %>">
    <div class="row">
      <div class="col-sm-12">
        <div class="input-group">
          <span class="input-group-addon"><i class="fa fa-lock"></i></span>
          <%= f.password_field :admin_password, autofocus: true, placeholder: t('.form.admin_password'), class: "form-control" %>
        </div>
        <p class="help-block">
          <% if @setting.errors.has_key?(:admin_password) %>
          <%= @setting.errors[:admin_password].join('<br>').html_safe %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
</div>
<div class="panel-footer">
  <div class="pull-left">
    <%= f.submit t('.form.reset'), type: 'reset', class: 'btn btn-default pull-left' %>
  </div>
  <div class="pull-right">
    <%= f.submit t('.form.submit'), class: 'btn btn-secondary' %>
  </div>
</div>
<% end %>

app/views/admin/setting/page_info.html.erb
<% provide(:og_title, t('.title')) %>
<% provide(:og_description, Setting.seo_description) %>
<% provide(:keywords, Setting.seo_keywords) %>
<% provide(:meta_image, Setting.featured_image) %>
<div id="page-heading">
  <ol class="breadcrumb">
    <li>
      <%= link_to t('admin.title'), admin_path %>
    </li>
    <li>
      <%= link_to t('admin.setting.title'), admin_setting_page_info_path %>
    </li>
    <li>
      <%= t('.title') %>
    </li>
  </ol>
  <h1>
    <%= t('.title') %>
  </h1>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="tab-container tab-left" id="setting-tabs">
        <%= render 'setting_tabs' %>
        <%= form_for @setting, url: admin_setting_path, method: 'put' do |f| %>
        <%= hidden_field_tag :update_type, @current_tab %>
        <%= hidden_field_tag :redirect_path, admin_setting_page_info_path %>
        <div class="tab-content">
          <div class="tab-pane active">
            <%= render 'general_setting', f: f %>
          </div>
          <div class="tab-footer">
            <%= f.submit t('save'), class: 'btn btn-secondary btn-sm' %>
            <%= link_to t('cancel'), admin_path, class: 'btn btn-default btn-sm' %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div> <!-- container -->

app/views/admin/setting/seo.html.erb
<% provide(:og_title, t('.title')) %>
<% provide(:og_description, Setting.seo_description) %>
<% provide(:keywords, Setting.seo_keywords) %>
<% provide(:meta_image, Setting.featured_image) %>
<div id="page-heading">
  <ol class="breadcrumb">
    <li>
      <%= link_to t('admin.title'), admin_path %>
    </li>
    <li>
      <%= link_to t('admin.setting.title'), admin_setting_page_info_path %>
    </li>
    <li>
      <%= t('.title') %>
    </li>
  </ol>
  <h1>
    <%= t('.title') %>
  </h1>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="tab-container tab-left" id="setting-tabs">
        <%= render 'setting_tabs' %>
        <%= form_for @setting, url: admin_setting_path, method: 'put' do |f| %>
        <%= hidden_field_tag :update_type, @current_tab %>
        <%= hidden_field_tag :redirect_path, admin_setting_seo_path %>
        <div class="tab-content">
          <div class="tab-pane active">
            <%= render 'seo_setting', f: f %>
          </div>
          <div class="tab-footer">
            <%= f.submit t('save'), class: 'btn btn-secondary btn-sm' %>
            <%= link_to t('cancel'), admin_path, class: 'btn btn-default btn-sm' %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div> <!-- container -->

app/views/admin/setting/smtp.html.erb
<% provide(:og_title, t('.title')) %>
<% provide(:og_description, Setting.seo_description) %>
<% provide(:keywords, Setting.seo_keywords) %>
<% provide(:meta_image, Setting.featured_image) %>
<div id="page-heading">
  <ol class="breadcrumb">
    <li>
      <%= link_to t('admin.title'), admin_path %>
    </li>
    <li>
      <%= link_to t('admin.setting.title'), admin_setting_page_info_path %>
    </li>
    <li>
      <%= t('.title') %>
    </li>
  </ol>
  <h1>
    <%= t('.title') %>
  </h1>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="tab-container tab-left" id="setting-tabs">
        <%= render 'setting_tabs' %>
        <%= form_for @setting, url: admin_setting_path, method: 'put' do |f| %>
        <%= hidden_field_tag :update_type, @current_tab %>
        <%= hidden_field_tag :redirect_path, admin_setting_smtp_path %>
        <div class="tab-content">
          <div class="tab-pane active">
            <%= render 'smtp_setting', f: f %>
            <hr>
            <%= render 'test_smtp' %>
          </div>
          <div class="tab-footer">
            <%= f.submit t('save'), class: 'btn btn-secondary btn-sm' %>
            <%= link_to t('cancel'), admin_path, class: 'btn btn-default btn-sm' %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div> <!-- container -->