config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admin', controllers: { sessions: "admin/sessions", passwords: 'admin/passwords' }

  devise_for :users, skip: [:sessions],
                     path: '',
                     controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  as :user do
    delete 'signout' => 'devise/sessions#destroy', as: :destroy_user_session, path: 'auth'
    get '/auth/:provider/setup' => 'users/omniauth_callbacks#setup', as: :setup_omniauth
  end

  #
  # Sidekiq
  #
  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    Admin.authenticate(username, password)
  end
  mount Sidekiq::Web => '/sidekiq'

  #
  # Websocket
  # 
  get '/socket/:account_id' => 'socket#show'

  #
  # Admin Page
  #
  scope '/admin', as: 'admin' do
    get '/' => 'admin/dashboard#index'

    put '/:language/update' => 'admin/languages#update', as: 'language'

    get '/setting/profile' => 'admin/profile#edit'
    put '/setting/profile' => 'admin/profile#update'

    resources :administrators, controller: 'admin/administrators' do
      resources :permissions, only: [:create, :destroy, :update], controller: 'admin/permissions'
      collection do
        delete 'multi_destroy'
      end
    end

    resources :users, controller: 'admin/users', only: [:edit, :update, :destroy, :index] do
      collection do
        delete 'multi_destroy'
        put    'multi_add_coin'
      end
    end

    resources :pages, controller: 'admin/pages', except: [:show, :new, :create]

    resources :posts, controller: 'admin/posts', except: [:show] do
      collection do
        delete 'multi_destroy'
      end
    end

    resources :categories, controller: 'admin/categories', except: [:show] do
      collection do
        delete 'multi_destroy'
      end
    end

    resources :artists, controller: 'admin/artists', except: [:show] do
      collection do
        delete 'multi_destroy'
      end
    end

    resources :images, controller: 'admin/images', only: [:index, :create, :destroy] do
      collection do
        delete 'multi_destroy'
      end
    end

    resources :tutorials, controller: 'admin/tutorials', except: [:show, :new, :create] do
      collection do
        delete 'multi_destroy'
      end
    end

    resource :crawler, controller: 'admin/crawler', only: [:create, :destroy]

    resources :tabs, controller: 'admin/tabs', except: [:show] do
      collection do
        delete 'multi_destroy'
        get 'multi_upload' => 'admin/multi_upload_tabs#new'
        post 'multi_upload' => 'admin/multi_upload_tabs#create'
      end
    end

    resource :setting, controller: 'admin/setting', only: [:new, :create, :update]

    resource :test_smtp, controller: 'admin/test_smtp', only: [:new, :create]

    scope '/setting', as: 'setting' do
      %w(
        page_info
        social_networks
        seo
        adfly
        smtp
        recaptcha
      ).each do |path|
        get path, to: "admin/setting##{path}"
      end
    end
  end

  # Download url
  get '/download/:hash' => 'download#show', as: 'download'

  # Contact
  post '/contacts' => 'contact#create', as: 'contacts'

  #
  # User Page
  #
  root 'static_pages#locale'

  scope ':language' do
    get '/' => 'static_pages#home'
    resources :tabs, except: [:show], param: 't' do
      member do
        resources :tutorials, only: [:create]
        resource :favorites, only: [:create, :destroy]
      end
    end

    resources :tutorials, except: [:index, :new, :create, :edit, :update, :show, :destroy] do
      member do
        resource :likes, only: [:create, :destroy]
        resource :dislikes, only: [:create, :destroy]
      end
    end

    resources :posts

    get 'profile' => 'users/profile#show'
    get 'profile/tabs' => 'users/tabs#index', as: 'uploaded_tabs'
    delete 'profile/tabs/:t' => 'users/tabs#destroy', as: 'destroy_tab'

    get '/player' => 'tabs#show', as: 'tab_show'

    get '/embed/:sid' => 'embed#show', as: 'embed'

    %w(
      term
      introduce
      privacy
    ).each do |path|
      get path, to: "static_pages##{path}"
    end

    get 'search' => 'search#index'

    get '/contact' => 'contact#index', as: 'contact'

    get '/favorites' => 'favorites#index'
  end

  post '/rate' => 'rater#create', :as => 'rate'

  # devise_for :users, skip: [:sessions],
  #                       path: '',
  #                       controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # as :user do
  #   match 'signout' => 'devise/sessions#destroy', as: :destroy_user_session, path: 'auth', via: Devise.mappings[:user].sign_out_via
  #   get '/auth/:provider/setup' => 'users/omniauth_callbacks#setup', as: :setup_omniauth
  # end
end

app/models/admin.rb
# == Schema Information
#
# Table name: admins
#
#  id                      :integer          not null, primary key
#  email                   :string(255)      not null
#  username                :string(255)      not null
#  encrypted_password      :string(255)      not null
#  fullname                :string(255)
#  phone                   :string(255)
#  address                 :string(255)
#  avatar                  :string(255)
#  updated_password        :boolean          default(FALSE)
#  last_update_password_at :datetime
#  reset_password_token    :string(255)
#  reset_password_sent_at  :datetime
#  remember_created_at     :datetime
#  sign_in_count           :integer          default(0), not null
#  current_sign_in_at      :datetime
#  last_sign_in_at         :datetime
#  current_sign_in_ip      :string(255)
#  last_sign_in_ip         :string(255)
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#
# Indexes
#
#  index_admins_on_email                 (email) UNIQUE
#  index_admins_on_reset_password_token  (reset_password_token) UNIQUE
#

class Admin < ActiveRecord::Base
  attr_accessor :account, :system
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable,
  :trackable, :validatable, :authentication_keys => [:account]

  has_many :images, dependent: :destroy
  has_many :admin_permissions, dependent: :destroy
  has_many :permissions, through: :admin_permissions, source: :permission

  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, multiline: true

  def avatar
    return super if super
    "https://api.adorable.io/avatars/500/#{email.downcase}.png"
  end

  class << self
    include Filter

    def authenticate(username, password)
      admin = Admin.find_for_authentication(:username => username)
      admin.valid_password?(password) ? admin : nil
    end

    def find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if account = conditions.delete(:account)
        where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { value: account.downcase }]).first
      elsif conditions.has_key?(:username) || conditions.has_key?(:email)
        where(conditions.to_h).first
      end
    end

    def filter(params)
      searchable_columns = %w(id email fullname)

      search_scope = search_string(searchable_columns, params)

      if params[:order]
        sortable_columns = {
          '2' => 'email',
          '3' => 'username',
          '4' => 'fullname',
          '5' => 'created_at'
        }

        order_scope = sort_string(sortable_columns, params)
      else
        order_scope = 'created_at desc'
      end

      where(search_scope).order(order_scope)
    rescue => e
      ErrorNotification.send(e)
      Kaminari.paginate_array([])
    end
  end
end

app/models/image.rb
# == Schema Information
#
# Table name: images
#
#  id                      :integer          not null, primary key
#  admin_id                :integer          not null
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  attachment_file_name    :string(255)
#  attachment_content_type :string(255)
#  attachment_file_size    :integer
#  attachment_updated_at   :datetime
#

class Image < ActiveRecord::Base
  has_attached_file :attachment, styles: { original: '1024x', s500: '500x500#', s420: '420x300#', s200: '200x200#' },
                                 use_timestamp: false,
                                 url: '/images/:style/:image_id:image_ext',
                                 path: ':rails_root/public:url'

  validates_attachment_presence :attachment

  validates_attachment_file_name :attachment, matches: [/jpeg\Z/, /jpg\Z/, /png\Z/, /JPEG\Z/, /JPG\Z/, /PNG\Z/]

  do_not_validate_attachment_file_type :attachment

  after_validation :clean_paperclip_errors

  belongs_to :admin

  # Callbacks
  after_validation :clean_paperclip_errors

  # interpolate in paperclip
  Paperclip.interpolates :image_id do |image, _style|
    "#{format('IMG%010d', image.instance.id)}"
  end

  Paperclip.interpolates :image_ext do |image, _style|
    ".#{image.instance.attachment_content_type.split('/').last}"
  end

  def attachment_url(style = :s200)
    "#{Setting.app_url}#{attachment.url(style)}?#{Time.zone.now.to_i}"
  end

  def attachment_file_size_text
    format_mb(attachment_file_size)
  end

  class << self
    include Filter

    def filter(params)
      searchable_columns = %w(attachment_file_name)

      search_scope = search_string(searchable_columns, params)

      if params[:order]
        sortable_columns = {
          '2' => 'attachment_file_name',
          '3' => 'attachment_file_size',
          '4' => 'attachment_content_type',
          '5' => 'created_at'
        }

        order_scope = sort_string(sortable_columns, params)
      else
        order_scope = 'created_at desc'
      end

      where(search_scope).order(order_scope)
    rescue => e
      ErrorNotification.send(e)
      Kaminari.paginate_array([])
    end
  end

  private

  def clean_paperclip_errors
    errors.delete(:attachment)
  end

  def format_mb(size)
    conv = %w(bytes KB MB GB TB PB EB)
    scale = 1024
    ndx = 1
    return "#{size} #{conv[ndx - 1]}" if size < 2 * (scale**ndx)
    size = size.to_f
    [2, 3, 4, 5, 6, 7].each do |i|
      if size < 2 * (scale**i)
        return "#{format('%.1f', (size / (scale**(i - 1))))} #{conv[i - 1]}"
      end
    end
    ndx = 7
    "#{format('%.1f', (size / (scale**(ndx - 1))))} #{conv[ndx - 1]}"
  end
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < ApplicationController
  include Admin::ImagesHelper
  include Admin::ErrorsHelper
  include I18nHelper

  before_action :authenticate_admin!
  before_action :set_image, only: [:destroy]
  layout 'admin_dashboard'

  def index
    @count = Image.count
    if params[:format] == 'json'
      page = 1
      page = params[:start].to_i / params[:length].to_i + 1 unless params[:start].to_i.zero?

      images = current_admin.images.filter(params).page(page).per(params[:length].to_i)
      images_data = []
      images.each do |image|
        data = render_image_as_html(image)
        images_data << data
      end

      data = {
        'draw' => params[:draw].to_i,
        'recordsTotal' => images.count,
        'recordsFiltered' => images.total_count,
        'data' => images_data
      }

      render json: data
    else
      respond_to do |format|
        format.html
        format.js do
          @images = current_admin.images.page(params[:page]).per(12)
          @count  = @images.total_count
          @images = @images.group_by { |x| x.created_at.strftime('%d/%m/%Y') }
        end
      end
    end
  rescue => e
    ErrorNotification.send(e)
    render_error_or_redirect
  end

  def create
    @image = current_admin.images.new image_params

    data = if @image.save
             {
               id: @image.id,
               s200: @image.attachment_url(:s200),
               s420: @image.attachment_url(:s420),
               s500: @image.attachment_url(:s500),
               original: @image.attachment_url(:original)
             }
           else
             {
               name: image_params['attachment'].original_filename,
               errors: @image.errors.full_messages
             }
           end

    render json: data
  end

  def destroy
    @params = params
    @errors = []
    @filename = @image.attachment_file_name
    unless @image.destroy
      @errors << t_scope(params, 'fail', name: @filename)
    end
  rescue => e
    ErrorNotification.send(e)
    @errors = I18n.t('alert.system_error')
  end

  def multi_destroy
    ActiveRecord::Base.transaction do
      @params = params
      @errors = []
      @destroyed_images = []
      params[:image_ids].split(',').each do |image_id|
        image = begin
                  current_admin.images.find(image_id)
                rescue
                  nil
                end

        filename = image.attachment_file_name if image

        if image.nil?
          @errors << I18n.t('images.not_found')
          raise ActiveRecord::Rollback
        elsif image.destroy
          @destroyed_images << OpenStruct.new(id: image.id, attachment_file_name: filename)
        else
          @errors << t_scope(params, 'fail', name: image.attachment_file_name)
          raise ActiveRecord::Rollback
        end
      end
    end
  rescue => e
    ErrorNotification.send(e)
    @errors = I18n.t('alert.system_error')
  end

  private

  def set_image
    @image  = current_admin.images.find(params[:id])
  rescue
    nil
  end

  def image_params
    params.require(:image).permit(:attachment)
  end
end

app/helpers/admin/images_helper.rb
module Admin::ImagesHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::FormTagHelper
  include ActionView::Helpers::AssetTagHelper
  include ActionView::Helpers::UrlHelper
  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::NumberHelper
  include ActionView::Context

  def render_image_as_html(image)
    checkbox    = image_checkbox_html(image)
    attachment  = image_attachment_html(image)

    attachment_file_name = image.attachment_file_name
    attachment_file_size = image.attachment_file_size_text
    attachment_content_type = File.extname(image.attachment_file_name)[1..-1].upcase

    created_at  = I18n.l(image.created_at, format: :datetime)
    actions     = image_actions_html(image)
    [checkbox, attachment, attachment_file_name, attachment_file_size, attachment_content_type, created_at, actions]
  rescue => e
    ErrorNotification.send(e)
    []
  end

  private

  def image_checkbox_html(image)
    content_tag :div, class: 'text-center' do
      check_box_tag 'check-box', image.id, false, class: 'check-one'
    end
  end

  def image_attachment_html(image)
    image_tag image.attachment.url(:s200), class: 'img-responsive'
  end

  def image_actions_html(image)
    content_tag :div, class: 'actions', role: 'group' do
      concat(image_destroy_html(image))
    end
  end

  def image_destroy_html(image)
    options = {
      data: {
        filename: image.attachment_file_name,
        image_id: image.id,
        href: admin_image_path(id: image.id),
        toggle: 'tooltip'
      },
      title: I18n.t('destroy'),
      class: 'btn-destroy btn btn-danger btn-sm'
    }
    button_tag '', options do
      content_tag :i, '', class: 'fa fa-fw fa-trash-o'
    end
  end
end

app/views/admin/images/_modal_upload_images.html.erb
<div class="modal fade zoom" id="modal-upload-images">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">
          <%= t('.new') %>
        </h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <%= form_for(Image.new, url: admin_images_path, remote: true,  authenticity_token: true, html: { method: :post, multipart: true, id: "fileupload" }) do |f| %>
        <%= f.file_field :image, multiple: true, accept: ".jpg, .png, .jpeg", id: "choose-file-image", name: "image[attachment]", style: "display: none" %>
        <div class="row">
          <div class="col-lg-12">
            <div id="files" class="files row"></div>
            <center>
              <h3>
                <%= t(".drop_images_here") %>
              </h3>
              <div class="or-box">
                <span class="border"></span>
                <%= t(".or") %>
                <span class="border"></span>
              </div>
              <div class="fileupload-buttonbar">
                <span id="select-file" class="fileinput-button btn btn-default btn-lg">
                  <span><%= t(".select_file") %></span>
                </span>
              </div>
            </center>
          </div>
        </div>
        <% end %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script type="text/javascript">
$('#modal-upload-images').on('hidden.bs.modal', function (e){
  window.location.reload()
})

$("#select-file").click(function() {
  $("#choose-file-image").click()
})

$(function () {
  $('#fileupload').fileupload({
    dataType: 'json',
    acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i,
    disableImageResize: /Android(?!.*Chrome)|Opera/
    .test(window.navigator && navigator.userAgent),
    dropZone: $("#modal-upload-images #fileupload")
  }).on('fileuploadadd', function (e, data) {
    data.context = $('<div class="col-md-3 col-sm-4" />').appendTo('#files');
    $.each(data.files, function (index, file) {
      var node = $('<div class="image-thumbnail" /><br>')
      node.append($('<i class="fa fa-picture-o" />'));
      node.append($('<div class="progress progress-striped active" />').append('<div class="progress-bar progress-bar-secondary" style="width: 100%" />'))
      node.appendTo(data.context);
    });
  }).on('fileuploaddone', function (e, data) {
    file = data.result
    $.each(data.files, function (index) {
      if (file.s200) {
        $(data.context.children()[index]).html("<img class='upload-image' src='"+ file.s200 +"' />")
      } else if (file.errors) {
        $(data.context).remove()
        showMessage("<b>" + file.name + "</b><br> " + file.errors.join("<br>"), "error")
      }
    })
  }).on('fileuploadfail', function (e, data) {
    showMessage("<%= t('alert.system_error') %>.", "error")
  })
})
</script>

app/views/admin/images/destroy.js.erb
$('body').css("cursor", 'auto')
if($("#modal-select-images").length > 0){
  $("button.btn").removeProp("disabled")
  <% if @errors.empty? %>
  showMessage("<%= t_scope(@params, 'success', name: @filename).html_safe %>.", "success")
  $(".image-thumbnail[image-id=<%= @image.id %>]").parents('.col-md-3').remove()

  length = $(".image-thumbnail").length

  if(length == 0)
  {
    $("#uploaded-images").html('')
    $("#uploaded-images").append("<div class='alert alert-warning' id='alert-no-images'><%= t('images.no_data') %>.</div>")
  }

  <% else %>
  showMessage("<%= render_value(@errors) %>", "error")
  <% end %>

  $(".image-thumbnail.selected").each(function(){
    $(this).removeClass("selected")
  })

  $(".selected-image-count").text("")
  $("#btn-delete-images").fadeOut(0)
}
else{
  $("#modal-confirm-destroy #btn-confirm").removeClass("disabled")
  $("#modal-confirm-destroy #btn-cancel").prop("disabled", false)
  <% if @errors.empty? %>
  showMessage("<%= t_scope(@params, 'success', name: @filename).html_safe %>.", "success")
  $('.modal#modal-confirm-destroy').modal('hide');
  var row = $(".btn-destroy[data-image-id=<%= @image.id %>]").parents('tr')
  window.images_table.fnDeleteRow(row[0])
  object_count = parseInt($('.object-count').text()) - 1
  $('.object-count').text(object_count)
  <% else %>
  showMessage("<%= render_value(@errors) %>", "error")
  <% end %>
}

app/views/admin/images/index.html.erb
<% provide(:og_title, t('.title')) %>
<% provide(:og_description, Setting.seo_description) %>
<% provide(:keywords, Setting.seo_keywords) %>
<% provide(:meta_image, Setting.featured_image) %>
<div id="page-heading">
  <ol class="breadcrumb">
    <li>
      <%= link_to t('admin.title'), admin_path %>
    </li>
    <li>
      <%= t('.title') %>
    </li>
  </ol>
  <h1>
    <%= t('.title') %>
    <small><strong>(<span class="object-count"><%= number_with_delimiter(@count) %></span>)</strong></small>
    <%= button_tag '', class: 'btn has-text btn-danger btn-action pull-right', id: 'btn-multi-destroy-images' do %>
    <i class="fa fa-trash-o"></i>
    <%= t('.multi_destroy') %>
    <% end %>
    <%= button_tag '', class: 'btn pull-right btn-secondary has-text', id: 'btn-upload-images' do %>
    <i class="fa fa-upload"></i>
    <%= t('.new') %>
    <% end %>
  </h1>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped datatables table-bordered" id="table-images">
        <thead>
          <tr>
            <th class="text-center"><%= check_box_tag 'checkbox', '', false, id: 'check-all' %></th>
            <th><%= t('.table.attachment') %></th>
            <th><%= t('.table.attachment_file_name') %></th>
            <th><%= t('.table.attachment_file_size') %></th>
            <th><%= t('.table.attachment_content_type') %></th>
            <th><%= t('.table.created_at') %></th>
            <th><%= t('manage') %></th>
          </tr>
        </thead>
        <tbody></tbody>
      </table>
    </div>
  </div>
</div> <!-- container -->
<script type="text/javascript">
$(function(){
  window.selected_id = []
  $("#check-all").click(function () {
    $('.check-one').prop('checked', this.checked);
    showMultiBtnActions();
  });

  $("#table-images").on("click", ".check-one", function(){
    if($(".check-one").length == $(".check-one:checked").length) {
      $("#check-all").prop("checked", true);
    } else {
      $("#check-all").prop("checked", false);
    }
    showMultiBtnActions();
  });

  images_ajax = {
    url :"<%= admin_images_path %>?format=json",
    type: "get"
  }

  window.images_table = dataTableInitialize({
    element: $("#table-images"),
    un_sorted_arr: [0, 1, 6],
    ajax: images_ajax,
    sDom: "<'row'<'col-lg-6'l><'col-lg-6'f>r>t<'row'<'col-lg-12'p>>"
  })

  $("#btn-multi-destroy-images").click(function(){
    $("#launch-modal").html("<%=j render 'shared/modal_confirm_destroy' %>")
    $("#modal-confirm-destroy").find("#btn-confirm").attr("href", "<%= multi_destroy_admin_images_path %>?image_ids="+window.selected_id.join(','))
    $("#modal-confirm-destroy").find("h2").html("<%= t('.destroy_selected') %>?")
    $("#modal-confirm-destroy").modal({
      keyboard: false,
      backdrop: 'static'
    })
  })

  $("#table-images").on("click", ".btn-destroy", function(){
    $("#launch-modal").html("<%=j render 'shared/modal_confirm_destroy' %>")
    $("#modal-confirm-destroy").find("#btn-confirm").attr("href", $(this).data("href"))
    $("#modal-confirm-destroy").find("#confirm-text").html("<%= t('.title').mb_chars.downcase %> " + $(this).data('filename'))
    $("#modal-confirm-destroy").modal({
      keyboard: false,
      backdrop: 'static'
    })
  })

  $("#btn-upload-images").click(function(){
    $("#launch-modal").html("<%=j render 'modal_upload_images' %>")
    $("#modal-upload-images").modal({
      keyboard: false,
      backdrop: 'static'
    })
  })
});
function showMultiBtnActions(){
  window.selected_id = []
  if($(".check-one:checked").length > 0){
    $(".btn-action").fadeIn(0)
    $(".check-one:checked").each(function(){
      window.selected_id.push($(this).val())
    })
  }
  else{
    $(".btn-action").fadeOut(0)
    $("#check-all").prop("checked", false);
  }
}
</script>

app/views/admin/images/index.js.erb
$("#data-loading").remove()
<% if @count > 0 %>
<% unless @images.blank? %>
$("#alert-no-images").remove()
<% @images.each do |date, images| %>
$ele = $(".files[date=<%= date.to_datetime.to_i %>]")
if($ele.length > 0){
  <% images.each do |image| %>
    $ele.append("<div class='col-md-3 col-sm-4'><div class='image-thumbnail' image-id='<%= image.id %>'><i class='fa fa-check'></i><img class='upload-image' original='<%= image.attachment_url(:original) %>' s420='<%= image.attachment_url(:s420) %>' s500='<%= image.attachment_url(:s500) %>' src='<%= image.attachment_url(:s200) %>'></div><br></div>")
  <% end %>
}
else{
  $("#uploaded-images").append("<div class='row files' date='<%= date.to_datetime.to_i %>'><div class='col-lg-12'><h3><%= date %></h3><hr></div></div><br>")
  $ele = $(".files[date=<%= date.to_datetime.to_i %>]")
  <% images.each do |image| %>
    $ele.append("<div class='col-md-3 col-sm-4'><div class='image-thumbnail' image-id='<%= image.id %>'><i class='fa fa-check'></i><img class='upload-image' original='<%= image.attachment_url(:original) %>' s420='<%= image.attachment_url(:s420) %>' s500='<%= image.attachment_url(:s500) %>' src='<%= image.attachment_url(:s200) %>'></div><br></div>")
  <% end %>
}
<% end %>
<% else %>
window.stopLoading = true
<% end %>
<% else %>
$("#alert-no-images").remove()
$("#uploaded-images").append("<div class='alert alert-warning' id='alert-no-images'><%= t('images.no_data') %>.</div>")
<% end %>

app/views/admin/images/multi_destroy.js.erb
$('body').css("cursor", 'auto')
$("#modal-confirm-destroy #btn-confirm").removeClass("disabled")
$("#modal-confirm-destroy #btn-cancel").prop("disabled", false)
<% if @errors.empty? %>
<% @destroyed_images.each do |image| %>
showMessage("<%= t_scope(@params, 'success', name: image.attachment_file_name).html_safe %>.", "success")
$('.modal#modal-confirm-destroy').modal('hide');
var row = $(".btn-destroy[data-image-id=<%= image.id %>]").parents('tr')
window.images_table.fnDeleteRow(row[0])
object_count = parseInt($('.object-count').text()) - 1
$('.object-count').text(object_count)
window.selected_id = []
$(".check-one").prop("checked", false)
$("#check-all").prop("checked", false)
<% end %>
<% else %>
showMessage("<%= render_value(@errors) %>", "error")
<% end %>
setTimeout(function(){
  showMultiBtnActions()
}, 200)